When (re)generating the auto* stuff, check for additional dependencies beyond the regular build dependencies listed in debian/control.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -76,8 +76,14 @@ source-updates:
 		echo "Sorry, intltool doesn't work with this version of gettext."; \
 		echo "See http://bugzilla.gnome.org/show_bug.cgi?id=93238 ." ; \
 		echo "Use woody's gettext package instead." ; \
-		exit 1 ; \
+		exit 1; \
 	fi
+	@for additionaldependency in 'gnome-common' 'automake1.7' ; do \
+		if ! dpkg -l $$additionaldependency 2>&1 | grep -q '^ii' ; then \
+			echo "For this target the package \"$$additionaldependency\" must be installed. Aborting." ; \
+			exit 1; \
+		fi ; \
+	done
 
 	# Update files generated by autotools
 	env srcdir=`pwd` NOCONFIGURE=1 sh macros/autogen.sh $(confflags)
